### model
model_name_or_path: /home/liyou/training_data/zLLaMA-Factory-Qwen2-VL/saves_vital/M1

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json
print_param_status: false

### dataset
dataset: sft_data
template: qwen2_vl
cutoff_len: 8192
max_samples: 210000
overwrite_cache: true
preprocessing_num_workers: 128
num_train_epochs: 1.0

# stream mode
# streaming: true
# buffer_size: 1024
# cutoff_len: 8192
# preprocessing_batch_size: 1024
# preprocessing_num_workers: 64
# mix_strategy: interleave_over
# max_steps: 3000
# accelerator_config:
#   dispatch_batches: false

### output
output_dir: saves/1222_post_sft_v1
logging_steps: 1
save_steps: 750
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 3
learning_rate: 4.0e-6
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true
ddp_timeout: 180000000